### ISSUE TITLE
Passing String Values to API Functions

### ISSUE THREAD

**Issue by faridz88** [manishmalik/Modsecurity-nodejs#1]
Hi
I think string input values for function calls does not pass properly to API functions.
for example after running some functions:

``` node
modsecurity.msc_process_connection(transaction, "127.0.0.1", 12345, '127.0.0.1', 80);
modsecurity.msc_process_uri(transaction, "http://example.com", "GET", "1.2");
console.log(transaction);
```

I see unicode charachters for `m_serverIpAddress`, `m_method`, `m_httpVersion` & `m_clientIpAddress` Like:

```
m_serverIpAddress: '��v\u0001',
m_method: '��v\u0001',
m_httpVersion: '��v\u0001',
m_clientIpAddress: '��v\u0001',
```

I also tried changing `v8::String::Utf8Value` to `v8::String::AsciiValue` in `%typemap(in) unsigned char *` of `modsecurity/customTypemaps.i`. but nth has changed.

**Comment by manishmalik** [comment]
Hi, 
Can you please provide me these details :
1. Your environment details ? (which OS and its version you are using)
2. SWIG version
3. Nodejs version

Also, here you are using the ModSecurity's C API , which in my testing have couple of these type of error (mostly type mapping related issues). I will suggest you to use ModSecurity's C++ API instead, mainly because I have considered C++ apis mostly in my testing and found it to be more stable compared to C api. You may want to look [`regression_tests.js`](https://github.com/manishmalik/Modsecurity-nodejs/blob/master/tests/regression_tests.js) as an example of the C++ api for nodejs.

**Comment by faridz88** [comment]
I am using Ubuntu Server 14.04 LTS
Swig Version: swig-3.0.10
Nodejs Version: v0.10.46
I will test C++ APIs and report back.

**Comment by faridz88** [comment]
Using C++ API Functions, I still get the same results. I see that values for variables like `m_clientIpAddress` looks random and changes in every run.

My Complete test code:

``` node
var modsecurity = require("./build/Release/modsecurity");

var modsec = new modsecurity.ModSecurity();
modsec.setConnectorInformation("ModSecurity-test");

var debugLog = new modsecurity.DebugLog();
debugLog.setDebugLogFile('test.log');
debugLog.setDebugLogLevel(9);

rules = new modsecurity.Rules(debugLog);
ret = rules.load('SecRule ARGS "test-attack" "id:1, phase:2, log, deny, status:501"');
console.log(ret);
//modsecurity.msc_rules_dump(rules);
modsecTransaction = new modsecurity.Transaction(modsec, rules, null);
modsecIntervention = new modsecurity.ModSecurityIntervention();

modsecTransaction.processConnection("127.0.0.1", 12345, "127.0.0.1", 80);

//console.log(modsecIntervention.status);
console.log(modsecTransaction.m_serverIpAddress);
```

**Comment by manishmalik** [comment]
Thanks for providing these details.
After doing the initial bug isolation, its seems like the problem lies in type conversion from C/C++ string to javascript string. So, when you pass a string from nodejs to C/C++ it does the conversion correctly and stores that value in the C/C++ datatype. But when you tries to access the string from `Transaction` property (`modsecTransaction.m_serverIpAddress`) it fails to convert the C/C++ string back to javascript string.
How I validated this :
1. Try this rule : `'SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" "id:3123,log,deny,status:401" '` , which basically block the given IP address.
2. On running, `modsecTransaction.intervention(modsecIntervention);` right after `modsecTransaction.processConnection("127.0.0.1", 12345, "127.0.0.1", 80);` , in the above code snippet, you will observe a an intervention is generated with the status code of `401` which indicates the string have been passed correctly to underlying C/C++ apis.

**Comment by faridz88** [comment]
Thank you very much. Thats right. Checking `modsecTransaction.intervention(modsecIntervention)` after running processing functions shows that internal functions work correctly and the issue is passing string values from C++ API functions to Node js.
